# Generated by Django 3.1.7 on 2021-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210301_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal account'), (1, 'Main account')], default=0),
        ),
    ]
