# Generated by Django 3.1.7 on 2021-03-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210322_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal account'), (1, 'Main account'), (2, 'Smart contract account')], default=0),
        ),
    ]
