# Generated by Django 3.1.7 on 2021-03-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210324_1151'),
    ]

    operations = []
