# Generated by Django 3.2.12 on 2022-03-28 13:56

import qrcode
import qrcode.image.svg
from django.core.files.base import ContentFile
from django.db import migrations


def forwards(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    for acc in Account.objects.all():
        img = qrcode.make(
            f"algorand://{acc.address}", image_factory=qrcode.image.svg.SvgImage)
        cp = ContentFile(b'')
        img.save(cp)
        acc.qr_code.save('qr_code.svg', cp, save=False)
        acc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_qr_code'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
