version: '3.9'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Development.dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/:/app
      - /app/node_modules
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
