# Generated by Django 3.1.7 on 2021-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210308_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(),
        ),
    ]
