# Generated by Django 3.1.7 on 2021-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210308_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fee',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='projects.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
