# Generated by Django 3.1.7 on 2021-03-15 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20210315_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiary_list', through='projects.Assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
