# Generated by Django 3.1.7 on 2021-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210318_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Waiting')], default=2),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Finished'), (1, 'Invested')], default=1),
        ),
    ]
