# Generated by Django 3.1.7 on 2021-03-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210318_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
