# Generated by Django 3.1.7 on 2021-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210322_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
    ]
