# Generated by Django 3.2.6 on 2021-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fundraising'), (1, 'Active'), (2, 'Closed')], default=2),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tasks', models.ManyToManyField(related_name='tasks', to='projects.Task')),
            ],
        ),
    ]
