# Generated by Django 3.2.6 on 2021-12-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20211229_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
