# Generated by Django 3.2.6 on 2021-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20211230_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(related_name='milestones', to='projects.Milestone'),
        ),
    ]
