# Generated by Django 3.2.6 on 2022-01-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='tasks_batch',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tasks_rewards',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tasks_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='fac_adm_funds',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones_batch',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones_rewards',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='raised_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='project',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
    ]
