# Generated by Django 3.2.6 on 2022-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20220128_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='tasks_batch',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='tasks_rewards',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='tasks_total',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones_batch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones_rewards',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones_total',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
