# Generated by Django 3.2.6 on 2022-01-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20220131_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
    ]
