# Generated by Django 3.2.6 on 2022-01-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_task_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='raised_total',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total',
        ),
    ]
