# Generated by Django 3.2.6 on 2022-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20220131_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
