# Generated by Django 3.2.6 on 2022-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fundraising'), (1, 'Active'), (2, 'Closed')], default=0),
        ),
    ]
