# Generated by Django 3.2.6 on 2022-02-08 13:02

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FileField(null=True, upload_to=projects.models.upload_project_document),
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(null=True, upload_to=projects.models.upload_project_document),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to=projects.models.upload_project_image),
        ),
    ]
