# Generated by Django 3.2.12 on 2022-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20220210_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial'), (1, 'Created'), (2, 'Initialized'), (3, 'Postponed'), (4, 'Started'), (5, 'Finished'), (6, 'Deleted')], default=0),
        ),
    ]
