# Generated by Django 3.2.12 on 2022-02-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fundraising_duration',
        ),
    ]
