# Generated by Django 3.2.12 on 2022-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_project_fundraising_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_id',
            field=models.IntegerField(null=True),
        ),
    ]
