# Generated by Django 3.2.12 on 2022-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20220211_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial'), (1, 'To sync'), (2, 'Synced')], default=0),
        ),
    ]
