# Generated by Django 3.2.12 on 2022-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_assignment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Rejected'), (1, 'Accepted'), (0, 'Waiting')], default=0),
        ),
    ]
