# Generated by Django 3.2.12 on 2022-02-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='action',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('milestones', models.ManyToManyField(related_name='milestones', to='projects.Milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='actions',
            field=models.ManyToManyField(related_name='actions', to='projects.Action'),
        ),
    ]
