# Generated by Django 3.2.12 on 2022-02-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20220228_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
    ]
