# Generated by Django 3.2.12 on 2022-03-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_remove_task_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial'), (1, 'To sync'), (2, 'Synced')], default=0),
        ),
    ]
