# Generated by Django 3.2.12 on 2022-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_project_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fundraising'), (2, 'Active'), (3, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial'), (1, 'To sync'), (2, 'Synced')], default=1),
        ),
    ]
