# Generated by Django 3.2.12 on 2022-03-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_rename_state_assignment_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Area'), (3, 'Photo')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='data_tags',
            field=models.ManyToManyField(to='projects.DataTag'),
        ),
        migrations.AddField(
            model_name='task',
            name='data_type_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.datatypetag'),
        ),
    ]
