# Generated by Django 3.2.12 on 2022-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20220315_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatag',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
