# Generated by Django 3.2.12 on 2022-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_datatag_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batch_paid',
            field=models.BooleanField(default=False),
        ),
    ]
