# Generated by Django 3.2.12 on 2022-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_task_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maplink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
