# Generated by Django 3.2.12 on 2022-04-04 08:56

from django.db import migrations

def forwards(apps, schema_editor):
    Action = apps.get_model('projects', 'Action')

    for action in Action.objects.all():
        for milestone in action.milestones.all():
            for task in milestone.tasks.all():
                task.action = action
                task.milestone = milestone
                task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20220404_0855'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
