# Generated by Django 3.2.12 on 2022-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20220404_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
    ]
