# Generated by Django 3.2.12 on 2022-04-06 09:14

from django.db import migrations

def forwards(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.all():
        total = project.fac_adm_funds
        for action in project.actions.all():
            for milestone in action.milestones.all():
                for task in milestone.tasks.all():
                    total += task.batch
                    total += task.reward * task.count

        project.total = total
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_project_total'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
