# Generated by Django 3.2.13 on 2022-04-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20220406_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='datatag',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('pk',)},
        ),
    ]
