# Generated by Django 3.2.6 on 2022-02-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20220208_1302'),
        ('investments', '0003_auto_20210401_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='start',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
