# Generated by Django 3.2.12 on 2022-03-07 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0037_rename_state_assignment_sync'),
        ('investments', '0004_auto_20220208_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='sync',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial'), (1, 'To sync'), (2, 'Synced'), (3, 'Failed')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('investor', 'project')},
        ),
    ]
