# Generated by Django 3.2.13 on 2022-04-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_investment_sync'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set(),
        ),
    ]
