# Generated by Django 3.2.12 on 2022-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=26),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Rejected'), (1, 'Accepted'), (0, 'Waiting')], default=0),
        ),
    ]
