# Generated by Django 3.2.12 on 2022-03-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220223_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='state',
            new_name='sync',
        ),
    ]
