# Generated by Django 3.2.12 on 2022-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_rename_state_activity_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photo',
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.ManyToManyField(to='activities.Photo'),
        ),
    ]
