# Generated by Django 3.2.12 on 2022-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20220321_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photos',
            field=models.ManyToManyField(null=True, to='activities.Photo'),
        ),
    ]
