# Generated by Django 3.2.12 on 2022-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
