# Generated by Django 3.2.12 on 2022-03-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20220321_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Work'), (1, 'Batch')], default=0),
        ),
    ]
