# Generated by Django 3.2.12 on 2022-04-07 07:36

from django.db import migrations

def forwards(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    for activity in Activity.objects.all():
        activity.reward = activity.task.reward
        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_activity_type'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
