# Generated by Django 3.1.7 on 2021-03-24 11:51

from django.db import migrations, models
import django.db.models.deletion
import smart_contracts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_auto_20210322_0916'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=smart_contracts.models.default_secret, max_length=32)),
                ('program', models.BinaryField(blank=True, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
