# Generated by Django 3.1.7 on 2021-03-24 12:27

from django.db import migrations, models
import smart_contracts.models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='secret',
            field=models.CharField(default=smart_contracts.models.default_secret, max_length=64),
        ),
    ]
