# Generated by Django 3.1.7 on 2021-03-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210322_0916'),
        ('investments', '0001_initial'),
        ('smart_contracts', '0003_auto_20210324_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='investment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investments.investment'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
