# Generated by Django 3.1.7 on 2021-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0004_auto_20210325_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='program',
            field=models.TextField(blank=True, null=True),
        ),
    ]
