# Generated by Django 3.2 on 2021-06-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleTransfer',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=26)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CirclePayment',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=26)),
                ('fee', models.DecimalField(decimal_places=6, default=0, max_digits=26)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('pending', 'Peding'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
