# Generated by Django 3.2.6 on 2021-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mtnpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtnpayout',
            name='phone',
            field=models.CharField(default='+48000000000', max_length=16),
            preserve_default=False,
        ),
    ]
