# Generated by Django 3.2.12 on 2022-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mtnpayout_phone'),
    ]

    operations = [
    ]
