# Generated by Django 3.2.13 on 2022-04-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_mtnpayout_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircleTransfer',
        ),
    ]
