# Generated by Django 3.2.13 on 2022-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_circletransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtnpayout',
            name='transaction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
