# Generated by Django 3.1.7 on 2021-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210322_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='atomic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Opt-In action'), (1, 'Fueling action'), (2, 'Transfer')]),
        ),
    ]
