# Generated by Django 3.1.7 on 2021-03-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210324_1151'),
        ('transactions', '0005_auto_20210322_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Opt-In action'), (1, 'Fueling action'), (2, 'Transfer'), (3, 'Close account')]),
        ),
    ]
