# Generated by Django 3.1.7 on 2021-03-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210324_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_address',
        ),
    ]
