# Generated by Django 3.2 on 2021-05-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20210401_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='atomic',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='repeated_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Confirmed'), (2, 'Pending')], default=2),
        ),
    ]
