# Generated by Django 3.2 on 2021-05-06 11:18

from django.db import migrations


def migrate_fields(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Transaction.objects.all().update(status=1)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20210506_1109'),
    ]

    operations = [
        migrations.RunPython(
            migrate_fields, reverse_code=migrations.RunPython.noop),
    ]
