# Generated by Django 3.2 on 2021-05-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20210506_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='atomic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='atomic_prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_atomic_transaction', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='repeated_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_transaction', to='transactions.transaction'),
        ),
    ]
