# Generated by Django 3.1.7 on 2021-03-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beneficiary'), (1, 'Facilitator'), (2, 'Investor'), (3, 'Administrator')], default=0),
        ),
    ]
