# Generated by Django 3.1.7 on 2021-03-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210308_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='village',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
