# Generated by Django 3.2.6 on 2021-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210316_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_type', models.PositiveSmallIntegerField(choices=[(0, 'Profit company'), (1, 'Nonprofit company'), (2, 'Individual'), (3, 'Goverment donor'), (4, 'Other')], null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('statement', models.CharField(blank=True, max_length=1023, null=True)),
                ('principal', models.CharField(blank=True, max_length=511, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
