# Generated by Django 3.2.12 on 2022-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Beneficiary'), (1, 'Facilitator'), (2, 'Investor'), (0, 'Administrator')], default=3),
        ),
    ]
